django_shoppingmall/urls.py
from django.contrib import admin
from django.urls import path
from users.views import home, RegisterView, LoginView, logout
from product.views import (
    ProductRegister, ProductList, ProductListAPI, ProductDetailAPI, ProductDetailView
)
from order.views import OrderCreate, OrderList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('logout/',logout),
    path('product/register/', ProductRegister.as_view()),
    path('product/list/', ProductList.as_view()),
    path('product/<int:pk>', ProductDetailView.as_view()),
    path('api/product/', ProductListAPI.as_view()),
    path('api/product/<int:pk>', ProductDetailAPI.as_view()),
    path('order/create/', OrderCreate.as_view()),
    path('order/', OrderList.as_view()),
]

order/models.py
from django.db import models

class Order(models.Model):
    user = models.ForeignKey('users.Users', verbose_name = "사용자", on_delete = models.CASCADE)
    product = models.ForeignKey('product.Product',verbose_name = "상품", on_delete = models.CASCADE)
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name="등록시간")
    quantity = models.IntegerField(verbose_name="수량")

    def __str__(self):
        return str(self.user) + ' ' + str(self.product)
    
    class Meta:
        db_table = "Shoppingmall_Order"
        verbose_name = "주문"
        verbose_name_plural = "주문"

order/forms.py
from django import forms
from .models import Order
from users.models import Users
from product.models import Product

class OrderForm(forms.Form):
    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
    
    quantity = forms.IntegerField(
        error_messages={'required':"수량을 입력하세요."},
        label = "수량"
    ) 
    product = forms.IntegerField(
        error_messages={'required':"상품을 입력하세요."},
        label = "상품", widget = forms.HiddenInput
    )

    def clean(self):
        cleaned_data = super().clean()
        quantity = cleaned_data.get('quantity')
        product = cleaned_data.get('product')
        user = self.request.session.get('user')

    
        if not(quantity and product and user):
            self.add_error('quantity', "수량이 없습니다.")
            self.add_error('product', "상품이 없습니다.")

product/forms.py
from django import forms
from .models import Product

class RegisterForm(forms.Form):
    name = forms.CharField(
        error_messages={'required':"상품명을 입력하세요."},
        max_length = 32, label = "상품명"
    )
    price = forms.IntegerField(
        error_messages={'required' : "가격을 입력하세요."},
        label = "가격"
    )
    stock = forms.IntegerField(
        error_messages={'required':"수량을 입력하세요"},
        label = "재고"
    )
    description = forms.CharField(
        error_messages={'required':"상품 설명을 입력하세요"},
        label = "상품 설명"
    )

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        price = cleaned_data.get('price')
        stock = cleaned_data.get('stock')
        description = cleaned_data.get('description')

        if not (name and price and stock and description):
            self.add_error('name', "값이 없습니다.")
            self.add_error('price', "값이 없습니다.")
            self.add_error('stock', "값이 없습니다.")
            self.add_error('description', "값이 없습니다.")

order/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.db import transaction

from .forms import OrderForm
from .models import Order
from users.models import Users
from product.models import Product
from users.decorators import login_required


@method_decorator(login_required, name = 'dispatch')
class OrderCreate(FormView):
    form_class = OrderForm
    success_url = '/product/list'

    def form_valid(self, form):
        with transaction.atomic():
            prod = Product.objects.get(pk=form.data.get('product'))
            order = Order(
                quantity = form.data.get('quantity'),
                product = prod,
                user = Users.objects.get(email = self.request.session.get('user'))
            )
            print(order)
            order.save()

            prod.stock -= int(form.data.get('quantity'))
            prod.save()
        return super().form_valid(form)

    
    def form_invalid(self, form):
        return redirect('/product/'+str(form.data.get('product')))
    

    def get_form_kwargs(self, **kwargs):
        kw = super().get_form_kwargs(**kwargs)
        kw.update({
            'request':self.request
        })
        return kw


@method_decorator(login_required, name = 'dispatch')
class OrderList(ListView):
        # model = Order 을 해버리면 문제점이 뭐냐면, 로그인한 사용자에 대한 주문 정보만 나오면 되는데
        # 모든 사용자에 대한 주문 정보가 나온다. 그래서 session을 통해서 email 값을 받아오는 것이 필요하다.
        # queryset을 통해서 session 값 가져오는 것
    #model = Order
    template_name = "order.html"
    context_object_name = 'order_list'

    def get_queryset(self, **kwargs):
        queryset = Order.objects.filter(user__email = self.request.session.get('user'))
        return queryset

templates/base.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name = "viewport" content = "width = device-width, initial - scale = 1"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src = "https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        {% block header %}
        {% endblock %}
    </head>
    <body>
        <div class="container">
            {% block contents%}
            {% endblock %}
        </div>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block contents %}

{{user}}

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block contents %}

<div class = "row mt-5">
    <div class = "col-12 text-center">
        <h1>로그인</h1>
    </div>
</div>

<div class = "row mt-5">
    <div class = "col-12">
        <form method = "POST" action = ".">
            {% csrf_token %}
            {% for field in form %}
            <div class = "form-group">
                <label for = "{{ field.id_for_label }}">{{field.label}}</label>
                <input type = "{{field.field.widget.input_type}}" class = "form-control" id = "{{field.id_for_label}}"
                placeholder="{{field.label}}" name = "{{field.name}}">
            </div>
            {% if field.errors %}
            <span style = "color:red">{{field.errors}}</span>
            {% endif %}
            {% endfor %}
            
            <button type = "submit" class = "btn btn-primary">로그인</button>
        </form>
    </div>
</div>

{% endblock %}

templates/order.html
{% extends 'base.html' %}
{% load humanize %}
{% block contents %}

<div class = "row mt-5">
    <div class = "col-12">
        <table class = "table table-dark">
            <thead class = "thead thead-dark">
                <tr>
                    <td scope = "col">#</td>
                    <td scope = "col">상품명</td>
                    <td scope = "col">수량</td>
                    <td scope = "col">주문날짜</td>
                </tr>
            </thead>
            <tbody class = "text-light">
                {% for order in object_list %}
                <tr>
                    <td scope = "col">{{order.id}}</td>
                    <td>{{order.product}}</td>
                    <td>{{order.quantity | intcomma}}개</td>
                    <td>{{order.registered_date | date:'Y-m-d H:i'}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/product_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block contents %}

<div class = "row mt-5">
    <div class = "col-12">
        <div class = "card" style = "width:100%">
            <div class = "card-body">
                <h5 class = "card-title">{{product.name}}</h5>
            </div>
            <ul class = "list-group list-group-flush">
                <li class = "list-group-item">
                    <form method = "POST" action = "/order/create/">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class = "form-group">
                            {% ifnotequal field.name 'product' %}
                            <label for = "{{field.id_for_label}}">{{field.label}}</label>
                            {% endifnotequal %}
                            <input type = "{{field.field.widget.input_type}}" class = "form-control" id = "{{field.id_for_label}}"
                            placeholder="{{field.label}}" name = "{{field.name}}"
                            value = "{% ifequal field.name 'product' %} {{product.id}} {% endifequal %}">
                        </div>
                        {% if field.errors %}
                        <span style = "color:red">{{field.errors}}</span>
                        {% endif %}
                        {% endfor %}
                        <button type = "submit" class = "btn btn-primary">주문</button>
                    </form>
                </li>
                <li class = "list-group-item">상품 가격 : {{ product.price | intcomma }} 원</li>
                <li class = "list-group-item">남은 수량 : {{ product.stock}}</li>
                <li class = "list-group-item">등록 날짜 : {{ product.registered_date|date:'Y-m-d H:i'}}</li>
                    <!-- |safe 를 하지 않으면 태그가 텍스트로 인식되어 제대로 나오지 않는다. 
                    태그를 텍스트가 아닌 태그 자체로 인식하기 위해 |safe 하는 것.-->
                <li class = "list-group-item">{{ product.description|safe }} </li>
            </ul>
        </div>
    </div>
</div>

{% endblock %}

templates/product_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block header %}
<script>
    $(document).ready(function(){
        $.ajax({
            url : "/api/product",
            success : function(result){
                console.log(result)
            }
        });
    })

    function product_detail(id){
        $.ajax({
            url:"/api/product/"+id,
            success : function(result){
                $("#product-"+id).popover({
                    html : true,
                    content : result.name + "<br>" + result.price
                }).popover('show');
            }
        })
    }

    function product_leave(id){
        $("#product-"+id).popover('hide');
    }
</script>
{% endblock %}

{% block contents %}
<div class = "row mt-5">
    <div class = "col-12">
        <table class = "table table-dark">
            <thead class = "thead thead-dark">
                <td scope = "col">No.</td>
                <td scope = "col">상품명</td>
                <td scope = "col">가격</td>
                <td scope = "col">등록 날짜</td>
            </thead>
            <tbody class = "text-light">
                {% for product in object_list %}
                <tr>
                    <td scope = "col">{{product.id}}</td>
                    <td><a id = "product-{{product.id}}" onmouseenter = "product_detail( {{ product.id }} );" onmouseleave = "product_leave( {{product.id}} );"
                        href = "/product/{{product.id}}">{{ product.name }}</a></td>
                    <td>{{ product.price | intcomma }}원</td>
                    <td>{{ product.registered_date | date:'Y-m-d H:i'}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/product_register.html
{% extends 'base.html' %}

{% block header %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.js"></script>

<script>
    $(document).ready(function(){
        $('#id_description').summernote({
            height:300
        });
    });
</script>
{% endblock %}

{% block contents %}
<div class = "row mt-5">
    <div class = "col-12 text-center">
        <h1>상품 등록</h1>
    </div>
</div>

<div class = "row mt-5">
    <div class = "col-12">
        <form method = "POST" action = ".">
            {% csrf_token %}
            {% for field in form %}
            <div class = "form-group">
                <label for = "{{field.id_for_label}}">{{field.label}}</label>
                {% ifequal field.name 'description' %}
                <textarea class = "form-control" name = "{{field.name}}" id = "{{field.id_for_label}}"></textarea>
                {% else %}
                <input type = "{{field.field.widget.input_type }}" class = "form-control" name = "{{field.name}}"
                id = "{{field.id_for_label}}" placeholder="{{field.label}}" name = "{{field.name}}">
                {% endifequal %}
            </div>
            {% if field.errors %}
            <span style = "color:red">{{field.errors}}</span>
            {% endif %}
            {% endfor %}

            <button type = "submit" class = "btn btn-primary">상품등록</button>
        </form>
    </div>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block contents %}

<div class = "row mt-5">
    <div class = "cl-12 text-center">
        <h1>회원가입</h1>
    </div>
</div>

<div class = "row mt-5">
    <div class = "col-12">
        <form method = "POST" action = ".">
            {% csrf_token %}
            {% for field in form %}
            <div class = "form-group">
                <label for = "{{fied.id_for_label}}">{{field.label}}</label>
                <input type = "{{field.field.widget.input_type}}" class = "form-control" id = "{{field.id_for_label}}"
                placeholder = "{{field.label}}" name = "{{field.name}}">
            </div>
            {% if field.errors %}
            <span style = "color:red">{{field.errors}}</span>
            {% endif %}
            {% endfor %}
            <button type = "submit" class = "btn btn-primary">회원가입</button>
        </form>
    </div>
</div>

{% endblock %}